# Generated by Sage Agent Compiler
# Target: Google ADK (Agent Development Kit)

from google.adk.agents import Agent
from typing import Callable, Any

# Tool definitions
def get_weather(city: str) -> str:
    """Get current weather for a city."""
    return f"The weather in {city} is sunny and 72°F"

def get_forecast(city: str, days: float) -> str:
    """Get weather forecast for upcoming days."""
    return f"{days}-day forecast for {city}: Mostly sunny"


# Agent definition
WeatherAgent = Agent(
    name="weatheragent",
    model="gemini-2.0-flash",
    description="An agent that provides weather information",
    instruction="""You are WeatherAgent. An agent that provides weather information

Available tools: get_weather, get_forecast""",
    tools=[get_weather, get_forecast],
)

# Export as root_agent for ADK compatibility
root_agent = WeatherAgent
class WeatherData:
    temperature: float
    humidity: float
    description: str
    city: str

