# Generated by Sage Agent Compiler
# Target: Google ADK (Agent Development Kit)

from google.adk.agents import Agent
from typing import Callable, Any

# Tool definitions
def greet(name: str) -> str:
    """Greet someone."""
    return f"Hello, {name}!"


# Agent definition
HelloAgent = Agent(
    name="helloagent",
    model="gemini-2.0-flash",
    description="A simple hello world agent",
    instruction="""You are HelloAgent. A simple hello world agent

Available tools: greet""",
    tools=[greet],
)

# Export as root_agent for ADK compatibility
root_agent = HelloAgent
class Message:
    content: str
    created_at: float

def add(a: float, b: float) -> float:
    return (a + b)

