// Generated by Sage Agent Compiler
// Do not edit manually

export class HelloAgent {
  static readonly description = "A simple hello world agent";
  static readonly version = "1.0.0";

  constructor() {
  }

  async greet(name: string): string {
    return `Hello, ${name}!`;
  }

  onUser_message(message: any) {
    const response = greet("World");
    this.emit("response", response);
  }
}

export interface Message {
  content: string;
  created_at: number;
}

export function add(a: number, b: number): number{
  return (a + b);
}
